- name: Create database container
  docker_container:
    name: postgres_db
    image: billonlj/tp-devops-cpe:database
    volumes:
      - /home/billonlj/CPE-Lyon/DevOps/Database/db-data
    networks:
      - name: "my-network"
